### PR TITLE
update to node-gyp@6.1

### LINKED ISSUE #9: Cant build on node.js v16
## Expected Behavior
I should be able to build this library

## Current Behavior
It does not build

## Possible Solution

--

## Steps to Reproduce

1. On node v16
2. run `npm build`

## Context (Environment)
```
❯ npm run-script configure 

> boost-geospatial-index@1.1.0 configure
> node-gyp configure

gyp info it worked if it ends with ok
gyp info using node-gyp@6.0.0
gyp info using node@16.15.0 | linux | x64
gyp info find Python using Python version 3.10.4 found at "/bin/python3"
(node:23292) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /bin/python3
gyp info spawn args [
gyp info spawn args   '/tmp/boost-geospatial-index/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/boost-geospatial-index/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/boost-geospatial-index/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pedro/.cache/node-gyp/16.15.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/pedro/.cache/node-gyp/16.15.0',
gyp info spawn args   '-Dnode_gyp_dir=/tmp/boost-geospatial-index/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/pedro/.cache/node-gyp/16.15.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/tmp/boost-geospatial-index',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "/tmp/boost-geospatial-index/node_modules/node-gyp/gyp/gyp_main.py", line 47, in <module>
    import gyp
  File "/tmp/boost-geospatial-index/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 10, in <module>
    import gyp.input
  File "/tmp/boost-geospatial-index/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 9, in <module>
    import gyp.common
  File "/tmp/boost-geospatial-index/node_modules/node-gyp/gyp/pylib/gyp/common.py", line 499, in <module>
    class OrderedSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/tmp/boost-geospatial-index/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.15.41_1
gyp ERR! command "/home/pedro/.nvm/versions/node/v16.15.0/bin/node" "/tmp/boost-geospatial-index/node_modules/.bin/node-gyp" "configure"
gyp ERR! cwd /tmp/boost-geospatial-index
gyp ERR! node -v v16.15.0
gyp ERR! node-gyp -v v6.0.0
gyp ERR! not ok 
```

### PR DESCRIPTION
**Pull request by revington**
Fixes #9

Update node-gyp from 6.0 to 6.1.
6.1 is really old but I don't know how much compatibility do you want to keep since in package.json it says
```javascript
  "engines": {
    "node": ">= 4.4.5",
    "npm": ">= 2.14.4"
  },
```
Anyway, I was able to build on v16.15 with this update.

### CODE REVIEW

**Comment by revington** [comment]
Sorry I forgot about the lockfile version 1 thing. Ignore this PR
